### PR TITLE
add getSensorDate()

### PR DESCRIPTION
**Pull request by RobTillaart**

### CODE REVIEW

**Comment by Beanow** [comment]
Yields for me: `DATE:	3022021`
Seems right, albeit a little unintuitive as the leading zero is missing on 03-02-2021.

```cpp
  uint32_t dd = AGS.getSensorDate();
  Serial.print("DATE:\t");
  Serial.println(dd, HEX);
```

**Comment by RobTillaart** [comment]
@Beanow 
I think I leave this for now as it is mainly for debugging. Alternative would be 9 bytes char array. 
For an UNO or Tiny85 this is "a lot" 

- need to document changes in the readme (tomorrow)

**Comment by RobTillaart** [comment]
Alternative could be to make it  **DA030221**
leaving out the 20 century and add DA for date for it ?

Could also follow the ISO 8601 
- start with year, followed by month, day,  then it would be 20210203 - that would solve it with an ISO standard :)

**Comment by Beanow** [comment]
The ISO 8601 style seems like a nice solution to me. I tend to use that in a lot of contexts, for example in filenames because alphabetical sorting matches date sorting.

**Comment by RobTillaart** [comment]
Exactly that!

**Pull request merged**
